spring.application.name=youtube-monetization

# PostgreSQL
spring.datasource.url=jdbc:postgresql://pg:5432/studs
spring.datasource.username=s408367
spring.datasource.password=QpjZpMmemnlctw7E
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# MinIO
minio.endpoint=http://localhost:8378
minio.access-key=minio
minio.secret-key=minio12345
minio.bucket.uploaded=uploaded-videos
minio.bucket.published=published-videos

# File upload limits
spring.servlet.multipart.max-file-size=110MB
spring.servlet.multipart.max-request-size=110MB

server.port=8368