spring.application.name=youtube-monetization


spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
spring.datasource.password=KosPrav1979
spring.datasource.driver-class-name=org.postgresql.Driver


spring.datasource.xa.data-source-class-name=org.postgresql.xa.PGXADataSource
spring.datasource.xa.properties.user=postgres
spring.datasource.xa.properties.password=KosPrav1979
spring.datasource.xa.properties.databaseName=test
spring.datasource.xa.properties.serverName=localhost
spring.datasource.xa.properties.portNumber=5432


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


spring.jta.enabled=true
spring.jta.narayana.transaction-manager-id=1


minio.endpoint=http://localhost:9000
minio.access-key=minio
minio.secret-key=minio12345
minio.bucket.uploaded=uploaded-videos
minio.bucket.published=published-videos


spring.servlet.multipart.max-file-size=110MB
spring.servlet.multipart.max-request-size=110MB

server.port=8080


jwt.secret=bXlTdXBlclNlY3JldEtleUZvckpXVEF1dGhlbnRpY2F0aW9uMjAyNQ==
jwt.expiration-ms=86400000


spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jms.activemq.ActiveMQAutoConfiguration


app.stomp.host=localhost
app.stomp.port=61613
app.stomp.login=admin
app.stomp.passcode=admin


spring.quartz.job-store-type=memory
spring.quartz.auto-startup=true


spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false


bitrix24.webhook-url=https://b24-5io913.bitrix24.ru/rest/1/r9y5utdbp7nihv2m/
bitrix24.responsible-id=1


app.cleanup.uploading-timeout-hours=24


app.node.id=node1


logging.file.name=logs/app.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7
logging.level.org.example=INFO
logging.level.com.arjuna=INFO
logging.level.org.jboss.narayana=INFO
logging.level.org.springframework.transaction=WARN
